In [ ]:
('''Q1. Creating a DataFrame
Create a Pandas DataFrame using a Python dictionary with the following columns
Product
Region
Sales
Quantity''')

In [1]:
import pandas as pd

# Creating a Python dictionary with sample data
data_q1 = {
    'Product': ['Laptop', 'Mouse', 'Keyboard', 'Monitor', 'Headphones'],
    'Region': ['East', 'West', 'North', 'South', 'East'],
    'Sales': [1200, 25, 75, 300, 150],
    'Quantity': [2, 5, 3, 1, 4]
}

# Creating the DataFrame
df_q1 = pd.DataFrame(data_q1)

# Displaying the DataFrame
df_q1

      Product Region  Sales  Quantity
0      Laptop   East   1200         2
1       Mouse   West     25         5
2    Keyboard  North     75         3
3     Monitor  South    300         1
4  Headphones   East    150         4

In [12]:
import pandas as pd 

df = pd.read_csv('C:/Users/deora/Downloads/Retail_dataset.csv')

In [ ]:
('''Q2. Data Inspection

Perform the following inspection tasks:

Display the first 5 rows of the dataset.

Display the last 5 rows.

Show the structure of the dataset using info().

Display the shape of the dataset.''')

In [13]:
# 1. Display the first 5 rows
print("First 5 rows:")
display(df.head())

# 2. Display the last 5 rows
print("\nLast 5 rows:")
display(df.tail())

# 3. Show the structure of the dataset using info()
print("\nDataset Structure:")
df.info()

# 4. Display the shape of the dataset
print("\nDataset Shape:")
print(df.shape)

First 5 rows:

   Order_ID Customer   Product Region  Sales  Quantity
0      1001    Sneha    Laptop   West   1056         2
1      1002     Neha    Tablet  South    904         7
2      1003    Meera    Laptop  South   1597         5
3      1004    Rohan  Keyboard  North    777         8
4      1005    Priya     Phone  South   2028         4

Last 5 rows:

    Order_ID Customer   Product Region  Sales  Quantity
85      1086    Pooja    Laptop   East   1330         2
86      1087    Anita  Keyboard   West    741         3
87      1088    Karan   Monitor   East    875         2
88      1089      Raj    Tablet  North   2213         5
89      1090    Priya    Laptop  South   1270         2

Dataset Structure:
<class 'pandas.DataFrame'>
RangeIndex: 90 entries, 0 to 89
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Order_ID  90 non-null     int64
 1   Customer  90 non-null     str
 2   Product   90 non-null     str
 3   Region    90 non-null     str
 4   Sales     90 non-null     int64
 5   Quantity  90 non-null     int64
dtypes: int64(3), str(3)
memory usage: 4.3 KB

Dataset Shape:
(90, 6)

In [ ]:
('''Q3. Column Selection

Select and display only the following columns:

Product

Region

Sales''')

In [14]:
# Selecting specific columns
selected_columns = df[['Product', 'Region', 'Sales']]
selected_columns.head()

    Product Region  Sales
0    Laptop   West   1056
1    Tablet  South    904
2    Laptop  South   1597
3  Keyboard  North    777
4     Phone  South   2028

In [ ]:
('''Q4. Indexing using .loc

Using .loc, perform the following:

Display the row with index 10.

Display the Sales value of the row with index 20''')

In [15]:
# 1. Display the row with index 10
print("Row at index 10:")
print(df.loc[10])

# 2. Display the Sales value of the row with index 20
print("\nSales value at index 20:")
print(df.loc[20, 'Sales'])

Row at index 10:
Order_ID       1011
Customer        Raj
Product     Monitor
Region        North
Sales          1693
Quantity          6
Name: 10, dtype: object

Sales value at index 20:
1021

In [ ]:
('''Q5. Indexing using .iloc

Using .iloc, display:

The first 6 rows and first 4 columns.

The Sales value from the 3rd row.''')

In [16]:
# 1. First 6 rows and first 4 columns
print("First 6 rows and first 4 columns:")
display(df.iloc[:6, :4])

# 2. Sales value from the 3rd row (index 2)
# The 'Sales' column is at column position index 4
print("\nSales value from the 3rd row:")
print(df.iloc[2, 4])

First 6 rows and first 4 columns:

   Order_ID Customer   Product Region
0      1001    Sneha    Laptop   West
1      1002     Neha    Tablet  South
2      1003    Meera    Laptop  South
3      1004    Rohan  Keyboard  North
4      1005    Priya     Phone  South
5      1006    Rahul    Tablet   West

Sales value from the 3rd row:
1597

In [ ]:
('''Q6. Row Slicing

Display:

The first 10 rows of the dataset.

Rows 15 to 25.''')

In [17]:
# 1. The first 10 rows
print("First 10 rows:")
display(df.iloc[:10])

# 2. Rows 15 to 25 (inclusive of index 25)
print("\nRows 15 to 25:")
display(df.loc[15:25])

First 10 rows:

   Order_ID Customer   Product Region  Sales  Quantity
0      1001    Sneha    Laptop   West   1056         2
1      1002     Neha    Tablet  South    904         7
2      1003    Meera    Laptop  South   1597         5
3      1004    Rohan  Keyboard  North    777         8
4      1005    Priya     Phone  South   2028         4
5      1006    Rahul    Tablet   West    638         2
6      1007     Amit   Monitor  South   1004         7
7      1008    Sneha   Monitor   East   1269         8
8      1009    Priya     Phone  North    827         8
9      1010     Amit     Phone   West   1998         4

Rows 15 to 25:

    Order_ID Customer  Product Region  Sales  Quantity
15      1016    Karan  Monitor   West    796         3
16      1017     Neha   Laptop   East   2015         2
17      1018    Anita    Phone  North   1637         3
18      1019     Amit    Phone   East    748         7
19      1020     Neha   Laptop   West   1503         6
20      1021    Priya   Laptop  North   1021         4
21      1022      Raj   Tablet  South    886         7
22      1023    Rahul   Laptop  South   2267         3
23      1024    Karan  Monitor   East    814         7
24      1025    Meera  Monitor   West   1926         6
25      1026    Anita   Tablet   East    839         5

In [ ]:
('''Q7. Filtering Data

Filter the dataset to display:

Rows where Region = "East".

Rows where Sales > 1500.''')

In [18]:
# 1. Filter by Region = "East"
print("Rows where Region is East:")
display(df[df['Region'] == 'East'].head())

# 2. Filter by Sales > 1500
print("\nRows where Sales > 1500:")
display(df[df['Sales'] > 1500].head())

Rows where Region is East:

    Order_ID Customer  Product Region  Sales  Quantity
7       1008    Sneha  Monitor   East   1269         8
11      1012    Rahul   Laptop   East   1022         5
16      1017     Neha   Laptop   East   2015         2
18      1019     Amit    Phone   East    748         7
23      1024    Karan  Monitor   East    814         7

Rows where Sales > 1500:

    Order_ID Customer  Product Region  Sales  Quantity
2       1003    Meera   Laptop  South   1597         5
4       1005    Priya    Phone  South   2028         4
9       1010     Amit    Phone   West   1998         4
10      1011      Raj  Monitor  North   1693         6
13      1014    Rohan    Phone  South   2078         3

In [ ]:
('''Q8. Multiple Condition Filtering

Display rows where:

Region is West

Sales is greater than 1200''')

In [19]:
# Multiple conditional filtering using &
filtered_west_sales = df[(df['Region'] == 'West') & (df['Sales'] > 1200)]
filtered_west_sales.head()

    Order_ID Customer   Product Region  Sales  Quantity
9       1010     Amit     Phone   West   1998         4
19      1020     Neha    Laptop   West   1503         6
24      1025    Meera   Monitor   West   1926         6
29      1030    Rohan   Monitor   West   1932         5
42      1043    Meera  Keyboard   West   1515         6

In [ ]:
('''Q9. Descriptive Statistics

Generate summary statistics using:

describe()

From the result identify:

Mean sales value

Maximum quantity sold

Minimum sales value ''')

In [20]:
# Summary statistics
summary_stats = df.describe()
print("Summary Statistics:")
display(summary_stats)

# Identifying requested metrics
print(f"Mean sales value: {summary_stats.loc['mean', 'Sales']:.2f}")
print(f"Maximum quantity sold: {summary_stats.loc['max', 'Quantity']}")
print(f"Minimum sales value: {summary_stats.loc['min', 'Sales']}")

Summary Statistics:

          Order_ID        Sales   Quantity
count    90.000000    90.000000  90.000000
mean   1045.500000  1406.888889   4.700000
std      26.124701   531.748302   2.179836
min    1001.000000   515.000000   1.000000
25%    1023.250000   890.500000   3.000000
50%    1045.500000  1402.000000   5.000000
75%    1067.750000  1857.250000   7.000000
max    1090.000000  2455.000000   8.000000

Mean sales value: 1406.89
Maximum quantity sold: 8.0
Minimum sales value: 515.0

In [ ]:
('''Q10. Aggregation Analysis

Using the Sales column, calculate:

Total sales

Average sales

Maximum sales

Minimum sales ''')

In [21]:
# Performing individual aggregations on the Sales column
total_sales = df['Sales'].sum()
avg_sales = df['Sales'].mean()
max_sales = df['Sales'].max()
min_sales = df['Sales'].min()

print(f"Total sales: {total_sales}")
print(f"Average sales: {avg_sales:.2f}")
print(f"Maximum sales: {max_sales}")
print(f"Minimum sales: {min_sales}")

Total sales: 126620
Average sales: 1406.89
Maximum sales: 2455
Minimum sales: 515